feat: Runner creation
defenseunicorns/uds-package-gitlab-runner pull request #1
Opened 2024-01-22 22:18 UTC by TristanHoladay

2024-01-23 19:55 UTC, brandtkeller commented on CODEOWNERS
> +* @defenseunicorns/uds
The team might just need access in the repository settings?

2024-01-23 20:35 UTC, UnicornChance commented on CODEOWNERS
> +* @defenseunicorns/uds
hmm i think you're right, however i do not have admin permissions on this repo. Maybe @mikevanhemert  can help us with this.

2024-01-23 22:41 UTC, MxNxPx commented on release-please-config.json
i think it would be best if we could match uds-package-sonarqube's release-please config (wasn't ready when this branch was started, but now is in place)

2024-01-24 14:29 UTC, MxNxPx commented on docs/DEVELOPMENT_MAINTENANCE.md
> +1) An e2e test will be triggered
Remove this line (since the release please PR doesn't rerun tests)

2024-01-24 14:29 UTC, MxNxPx commented on docs/DEVELOPMENT_MAINTENANCE.md
> +1) If e2e passes, a new capability artifact will be published to the OCI registry
Remove `If e2e passes,`

2024-01-24 15:06 UTC, MxNxPx commented on tasks/publish.yaml
> +    default: "0.1.0"
need to set this to the same version used in the .release-please-manifest.json

2024-01-24 19:39 UTC, MxNxPx commented
some refactoring needed if we want it to use https://github.com/defenseunicorns/uds-common-tasks, but that could come in a later PR

2024-01-24 20:52 UTC, TristanHoladay commented
i think we should go ahead and merge this and move the tasks refactors to another PR. there's a little bit of weirdness meshing the local tasks with the remote ones based on some experimenting i'm doing.

2024-01-24 21:00 UTC, mjnagel commented on chart/templates/uds-package.yaml
> +        remoteNamespace: gitlab
Assuming this is for connecting to gitlab we should be able to lockdown to a port/pod selector I think?

2024-01-24 21:00 UTC, mjnagel commented on chart/templates/uds-package.yaml
> +    allow:
I think to spin up jobs the runner needs egress to the kube-api (since it creates pods per job)? Have you tested with a pipeline running with these netpols setup?

2024-01-24 21:00 UTC, mjnagel commented on renovate.json
> +    }
probably can drop this match?

2024-01-24 21:00 UTC, mjnagel commented on values/gitlab-runner-values.yaml
> +            image="alpine"
Not sure if I'm missing it but I think this + helper_image will need to be specified based on the flavor specifics?

2024-01-24 21:00 UTC, mjnagel commented on chart/templates/uds-package.yaml
> +    allow:
May also need an ingress and/or egress policy from/to the `gitlab-runner-sandbox` namespace to ensure proper comms between the jobs and the runner itself?

2024-01-24 21:06 UTC, TristanHoladay commented on chart/templates/uds-package.yaml
> +        remoteNamespace: gitlab
you're probably right on that. this is a mirror of FF netpols.

2024-01-25 13:47 UTC, UnicornChance commented on .github/workflows/test.yaml
> +
Yup, totally agree. Was in place for getting everything setup and then promptly forgotten.

2024-01-25 20:29 UTC, UnicornChance commented on tasks/test.yaml
> +      - description: Check Gitlab Runner Deployment
Bug here, the Deployment is successful but that doesn't mean that the gitlab runner is healthy, ex. the gitlab runner pod looks healthy but it's not actually registering with Gitlab via the secret.

2024-01-26 20:47 UTC, UnicornChance commented on tasks/test.yaml
> +      - description: Check Gitlab Runner Deployment
updated with new tests for checking health, restarts, and logs for successful gitlab runner pod deployment, init, and registration.

2024-01-26 20:49 UTC, UnicornChance commented on values/gitlab-runner-values.yaml
> +            image="alpine"
Update to have individual values files for reg1 and upstream. Both have their helper_image defined in different ways since BB supplies some of that to the reg1 chart for us.

2024-01-26 20:51 UTC, UnicornChance commented on chart/templates/uds-package.yaml
> +    allow:
Still have not been able to figure out a good way to test the pipeline running. Gitlab yolo chart is proving interesting to integrate with and even access standalone. Long term it seems best to utilize the uds-package-gitlab instead, which is also currently not in a great spot for integration but with @rjferguson21 's work to bring in the operator it should be usable soon.

2024-02-01 21:12 UTC, zachariahmiller requested changes
3 changes, all the same thing. Otherwise looks good.

2024-02-01 21:12 UTC, zachariahmiller commented on pkg-deps/rbac/zarf.yaml
> +  architecture: amd64
I dont think architecture should be specified here

2024-02-01 21:12 UTC, zachariahmiller commented on pkg-deps/gitlab/dev-secrets/zarf.yaml
> +  architecture: amd64
I dont think architecture should be specified here

2024-02-01 21:12 UTC, zachariahmiller commented on zarf.yaml
> +  architecture: amd64
I dont think architecture should be specified here

2024-02-01 21:20 UTC, zachariahmiller approved these changes

2024-02-01 21:29 UTC, rjferguson21 approved these changes

2024-02-01 21:35 UTC, merged