feat: add SETUID capability for gitlab runner container security context
defenseunicorns/uds-package-gitlab-runner pull request #116
Opened 2024-08-14 13:58 UTC by ericwyles

## Description

Add SETUID capability for gitlab runner container security context to allow running buildah inside the a container from the runners.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-gitlab-runner/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-08-14 16:11 UTC, Racer159 requested changes
I think this change should be fine but can you add a docs note to `configuration.md` to mention needing this `sysctl` setting? https://github.com/defenseunicorns/uds-rke2-image-builder/pull/81/files#diff-8c6b38593d0267b1fcfe569ffd1ab064b64bdecc6293bc967cded5f4b9c8bc13R15
(ideally in an admonition to call attention to it)

2024-08-14 17:29 UTC, Racer159 requested changes
Small tweak since it is only applicable to buildah and tools like it

2024-08-14 17:29 UTC, Racer159 commented on docs/configuration.md
> +> Any kubernetes node that will run GitLab Runner pods must set the sysctl `user.max_user_namespaces` value to nonzero. This is required to run builds inside Linux containers from the runner pods.
```suggestion
> Any kubernetes node that will run GitLab Runner pods to use tooling like [Buildah](https://buildah.io/) must set sysctl `user.max_user_namespaces` to a nonzero value. This is required to run these container builds inside Linux containers from the runner pods.
```

2024-08-14 21:48 UTC, bburky commented
CAP_SETUID is basically equivalent to root in the container. I understand there's a need for this for container builds, but I don't love seeing this be the default config for GitLab.

Do we support multiple configurations of gitlab runner groups (so this could be an optional config)? Do we support/suggest using dedicated nodes for gitlab runners (so that compromising CI doesn't compromise the whole cluster)?

Have we made any progress on using ephemeral EC2/VM-based runners? Let people have root in their CI (and use real `docker build`), if you've isolated them with a VM or dedicated EC2 instance.

2024-08-14 21:49 UTC, bburky commented
I guess DISABLE_RESTRICTCAPABILITIES_EXEMPTION is disabled by default. But it does end up enabled for all runners.

2024-08-14 22:02 UTC, Racer159 commented
> CAP_SETUID is basically equivalent to root in the container. I understand there's a need for this for container builds, but I don't love seeing this be the default config for GitLab.
> 
> Do we support multiple configurations of gitlab runner groups (so this could be an optional config)? Do we support/suggest using dedicated nodes for gitlab runners (so that compromising CI doesn't compromise the whole cluster)?
> 
> Have we made any progress on using ephemeral EC2/VM-based runners? Let people have root in their CI (and use real `docker build`), if you've isolated them with a VM or dedicated EC2 instance.

We do support running gitlab runners on their own cluster (you can give it a different gitlab URL and registration token) and it is an optional config (though defaulted) as written - we can undefault it or remove that part of the PR to only partially support Buildah in the runner (buildah can run without this but flags warnings and I would expect some container build operations would fail though haven't dug that far yet).

Not yet on fleeting runners though it is something still on the docket to setup for envs that can use it (really just AWS rn)

2024-08-14 22:44 UTC, Racer159 commented
Opened a draft PR for the fleeting plugin: https://github.com/defenseunicorns/uds-package-gitlab-runner/pull/117 - looks like it is out of beta now too cc @oates / @zachariahmiller

2024-08-15 14:33 UTC, zachariahmiller commented
> > CAP_SETUID is basically equivalent to root in the container. I understand there's a need for this for container builds, but I don't love seeing this be the default config for GitLab.
> > Do we support multiple configurations of gitlab runner groups (so this could be an optional config)? Do we support/suggest using dedicated nodes for gitlab runners (so that compromising CI doesn't compromise the whole cluster)?
> > Have we made any progress on using ephemeral EC2/VM-based runners? Let people have root in their CI (and use real `docker build`), if you've isolated them with a VM or dedicated EC2 instance.
> 
> We do support running gitlab runners on their own cluster (you can give it a different gitlab URL and registration token) and it is an optional config (though defaulted) as written - we can undefault it or remove that part of the PR to only partially support Buildah in the runner (buildah can run without this but flags warnings and I would expect some container build operations would fail though haven't dug that far yet).
> 
> Not yet on fleeting runners though it is something still on the docket to setup for envs that can use it (really just AWS rn)

Unless something has drastically changed recently it fails without SETUID and honestly i thought SETGUID in rootless. IIRC its on the mount, `buildah bud` and `buildah unshare`

2024-08-20 17:36 UTC, zachariahmiller commented on chart/templates/uds-policy-exemptions.yaml
> +{{- end }}
newline

2024-08-26 22:20 UTC, zachariahmiller commented on tests/journey/pipeline-run.test.ts
> +        const jobIDResp = await (await fetch(`https://gitlab.uds.dev/api/v4/projects/${projectId}/jobs`, { headers })).json()
We should probably pull out domain as a var as it was desired to have these tests be something that could be run from somewhere other than our CI in the future and domain would need to be provided.

2024-08-26 22:48 UTC, Racer159 requested changes

2024-08-26 22:48 UTC, Racer159 commented on tests/journey/pipeline-run.test.ts
> +    //await executeTest(sourceRepoName, expectedJobLogOutputs, expectedStatus)
commented code?

2024-08-26 22:59 UTC, Racer159 approved these changes
lgtm assuming tests pass

2024-08-26 23:00 UTC, ericwyles commented on tests/journey/pipeline-run.test.ts
> +        const jobIDResp = await (await fetch(`https://gitlab.uds.dev/api/v4/projects/${projectId}/jobs`, { headers })).json()
pulled this out to an env var!

2024-08-26 23:23 UTC, merged