chore: update custom network properties key
defenseunicorns/uds-package-gitlab-runner pull request #150
Opened 2024-12-09 15:04 UTC by codyshoffner

## Description

- Updating all instances of custom: [] to additionalNetworkAllow: []

## Related Issue

Fixes #

Relates to #
https://github.com/orgs/defenseunicorns/projects/118/views/12?pane=issue&itemId=87152090&issue=defenseunicorns%7Cuds-package-maintenance%7C5
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-gitlab/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-12-10 21:10 UTC, Racer159 requested changes

2024-12-10 21:10 UTC, Racer159 commented on chart/values.yaml
> +additionalNetworkAllowSandbox: []
Can we change this to:

```
sandbox:
  namespace: "###ZARF_VAR_RUNNER_SANDBOX_NAMESPACE###"

  # whether to have the Zarf Agent ignore the sandbox namespace
  zarfIgnore: true

  # whether to allow securityContext capabilities like SET_UID/SET_GID in the sandbox: https://github.com/defenseunicorns/uds-package-gitlab-runner/blob/main/docs/configuration.md#allow-setuid-and-setgid-security-capabilities
  enableSecurityCapabilityExceptions: false

  additionalNetworkAllow: []
```

2024-12-10 21:52 UTC, Racer159 requested changes

2024-12-10 21:52 UTC, Racer159 commented on chart/values.yaml
> +  namespace: "###ZARF_VAR_RUNNER_SANDBOX_NAMESPACE###"
You'll need to update these in docs and in the rest of the templates.

2024-12-10 22:31 UTC, codyshoffner commented on chart/templates/uds-policy-exemptions.yaml
> +{{- if .Values.kubernetesSandbox.enableSecurityExceptions }}
Is the intention to transition to `Exceptions` from `Capabilities`? Or did I goof that one?

2024-12-10 22:32 UTC, Racer159 commented on chart/templates/uds-policy-exemptions.yaml
> +{{- if .Values.kubernetesSandbox.enableSecurityExceptions }}
Yep the intention is to do that - it is more descriptive to what you are doing in UDS since it turns on a UDS Exception

2024-12-10 22:38 UTC, Racer159 requested changes

2024-12-10 22:38 UTC, Racer159 commented on values/common-values.yaml
> +kubernetesSandbox.enableSecurityExceptions: ###ZARF_VAR_ENABLE_SECURITY_CAPABILITIES###
```suggestion
kubernetesSandbox:
  enableSecurityExceptions: ###ZARF_VAR_ENABLE_SECURITY_CAPABILITIES###
```

2024-12-10 22:38 UTC, Racer159 commented on values/config-values.yaml
> +kubernetesSandbox.enableSecurityExceptions: ###ZARF_VAR_ENABLE_SECURITY_CAPABILITIES###
```suggestion
kubernetesSandbox:
  enableSecurityExceptions: ###ZARF_VAR_ENABLE_SECURITY_CAPABILITIES###
```

2024-12-11 20:53 UTC, Racer159 requested changes
Tests

2024-12-11 20:53 UTC, Racer159 commented on values/common-values.yaml
>    secret: gitlab-gitlab-runner-secret
Tests are failing bc line `77-81` in this file should be:
```yaml
     {{- if .Values.kubernetesSandbox.enableSecurityExceptions }}
      [runners.kubernetes.build_container_security_context]
        [runners.kubernetes.build_container_security_context.capabilities]
          add = ["SETUID", "SETGID"]
      {{- end }}
```

2024-12-11 21:21 UTC, Racer159 approved these changes

2024-12-11 21:55 UTC, merged