fix: update to the new runner registration system
defenseunicorns/uds-package-gitlab-runner pull request #93
Opened 2024-06-14 19:24 UTC by Racer159

## Description

This updates the registration system to the new runner authentication token (counting it as a bug fix as users have observed manual steps being needed in the current workflow).

## Related Issue

Fixes #74

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [X] Test, docs, adr added or updated as needed
- [X] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-gitlab-runner/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-06-14 21:48 UTC, zachariahmiller commented on zarf.yaml
> +      - "registry.gitlab.com/gitlab-org/ci-cd/gitlab-runner-ubi-images/gitlab-runner-helper-ocp:v17.0.0"
❤️

2024-06-18 21:12 UTC, Racer159 commented
New test regimen adds ~1 min 
![image](https://github.com/defenseunicorns/uds-package-gitlab-runner/assets/3977569/86e60f37-4757-4a09-aa95-f92e1c4c40ee)

2024-06-18 21:25 UTC, zachariahmiller commented on tasks/test.yaml
> +        cmd: cat bundle/uds-bundle.yaml | yq .metadata.version
```suggestion
        cmd: cat bundle/uds-bundle.yaml | ./uds zarf tools yq .metadata.version
```

2024-06-18 21:25 UTC, zachariahmiller commented on tasks/test.yaml
> +        cmd: cat bundle/uds-bundle.yaml | yq .metadata.name
```suggestion
        cmd: cat bundle/uds-bundle.yaml | ./uds zarf tools yq .metadata.name
```

2024-06-18 21:26 UTC, zachariahmiller requested changes

2024-06-18 21:26 UTC, zachariahmiller commented on tasks/test.yaml
> +      - cmd: ./uds zarf tools kubectl get secret -n gitlab gitlab-gitlab-runner-secret -o yaml | ./uds zarf tools yq 'del(.metadata.namespace,.metadata.resourceVersion,.metadata.uid) | .metadata.crea
raw kubectl in here and others

2024-06-21 20:49 UTC, Racer159 commented
Added breaking change since this now requires UDS Core [v0.22.0](https://github.com/defenseunicorns/uds-core/releases/tag/v0.22.0)

2024-06-21 21:37 UTC, ericwyles approved these changes

2024-06-26 20:07 UTC, zachariahmiller approved these changes

2024-06-26 20:07 UTC, merged